version: '3'
services:
  zeppelin:
    image: apache/zeppelin:0.10.0
    ports:
      - "8080:8080"
      - "4040:4040"
    environment:
      ZEPPELIN_LOG_DIR: /mnt/logs
      ZEPPELIN_NOTEBOOK_DIR: /mnt/notebook
      SPARK_HOME: /opt/spark
      ZEPPELIN_NOTEBOOK_STORAGE: org.apache.zeppelin.notebook.repo.VFSNotebookRepo
    volumes:
      - ./logs:/mnt/logs
      - ./notebook:/mnt/notebook
      - ./spark/spark-3.1.2-bin-hadoop3.2:/opt/spark
      - ./data:/mnt/data
